import 'package:flutter/material.dart';
import 'package:xterm/xterm.dart';

class TerminalThemeOption {
  const TerminalThemeOption({
    required this.key,
    required this.name,
    required this.type,
    this.theme,
  });

  final String key;
  final String name;
  final String type;
  final TerminalTheme? theme;
}

Color _hex(String value) {
  final normalized = value.replaceFirst('#', '');
  final rgb = normalized.length >= 6 ? normalized.substring(0, 6) : normalized;
  return Color(int.parse('ff$rgb', radix: 16));
}

TerminalTheme _theme({
  required String background,
  required String foreground,
  required String cursor,
  required String selectionBackground,
  required String black,
  required String red,
  required String green,
  required String yellow,
  required String blue,
  required String magenta,
  required String cyan,
  required String white,
  required String brightBlack,
  required String brightRed,
  required String brightGreen,
  required String brightYellow,
  required String brightBlue,
  required String brightMagenta,
  required String brightCyan,
  required String brightWhite,
}) {
  return TerminalTheme(
    cursor: _hex(cursor),
    selection: _hex(selectionBackground),
    foreground: _hex(foreground),
    background: _hex(background),
    black: _hex(black),
    red: _hex(red),
    green: _hex(green),
    yellow: _hex(yellow),
    blue: _hex(blue),
    magenta: _hex(magenta),
    cyan: _hex(cyan),
    white: _hex(white),
    brightBlack: _hex(brightBlack),
    brightRed: _hex(brightRed),
    brightGreen: _hex(brightGreen),
    brightYellow: _hex(brightYellow),
    brightBlue: _hex(brightBlue),
    brightMagenta: _hex(brightMagenta),
    brightCyan: _hex(brightCyan),
    brightWhite: _hex(brightWhite),
    searchHitBackground: _hex(yellow),
    searchHitBackgroundCurrent: _hex(blue),
    searchHitForeground: _hex(background),
  );
}

class TerminalThemeCatalog {
  static final Map<String, TerminalThemeOption> options = {
    'auto': const TerminalThemeOption(
      key: 'auto',
      name: 'Auto (Follow System)',
      type: 'auto',
    ),
    'termiusDark': TerminalThemeOption(
      key: 'termiusDark',
      name: 'Termius Dark',
      type: 'dark',
      theme: _theme(
        background: '#282a36',
        foreground: '#f8f8f2',
        cursor: '#f8f8f2',
        selectionBackground: '#f8f8f2',
        black: '#21222c',
        red: '#ff5555',
        green: '#50fa7b',
        yellow: '#f1fa8c',
        blue: '#8be9fd',
        magenta: '#bd93f9',
        cyan: '#8be9fd',
        white: '#f8f8f2',
        brightBlack: '#6272a4',
        brightRed: '#ff6e6e',
        brightGreen: '#69ff94',
        brightYellow: '#ffffa5',
        brightBlue: '#d6acff',
        brightMagenta: '#ff92df',
        brightCyan: '#a4ffff',
        brightWhite: '#ffffff',
      ),
    ),
    'termiusLight': TerminalThemeOption(
      key: 'termiusLight',
      name: 'Termius Light',
      type: 'light',
      theme: _theme(
        background: '#ffffff',
        foreground: '#2d2d2d',
        cursor: '#2d2d2d',
        selectionBackground: '#2d2d2d',
        black: '#000000',
        red: '#e74c3c',
        green: '#27ae60',
        yellow: '#f39c12',
        blue: '#3498db',
        magenta: '#9b59b6',
        cyan: '#1abc9c',
        white: '#95a5a6',
        brightBlack: '#34495e',
        brightRed: '#c0392b',
        brightGreen: '#229954',
        brightYellow: '#d68910',
        brightBlue: '#2980b9',
        brightMagenta: '#8e44ad',
        brightCyan: '#16a085',
        brightWhite: '#7f8c8d',
      ),
    ),
    'dracula': TerminalThemeOption(
      key: 'dracula',
      name: 'Dracula',
      type: 'dark',
      theme: _theme(
        background: '#282a36',
        foreground: '#f8f8f2',
        cursor: '#f8f8f2',
        selectionBackground: '#f8f8f2',
        black: '#21222c',
        red: '#ff5555',
        green: '#50fa7b',
        yellow: '#f1fa8c',
        blue: '#8be9fd',
        magenta: '#bd93f9',
        cyan: '#8be9fd',
        white: '#f8f8f2',
        brightBlack: '#6272a4',
        brightRed: '#ff6e6e',
        brightGreen: '#69ff94',
        brightYellow: '#ffffa5',
        brightBlue: '#d6acff',
        brightMagenta: '#ff92df',
        brightCyan: '#a4ffff',
        brightWhite: '#ffffff',
      ),
    ),
    'monokai': TerminalThemeOption(
      key: 'monokai',
      name: 'Monokai',
      type: 'dark',
      theme: _theme(
        background: '#272822',
        foreground: '#f8f8f2',
        cursor: '#f8f8f2',
        selectionBackground: '#f8f8f2',
        black: '#272822',
        red: '#f92672',
        green: '#a6e22e',
        yellow: '#f4bf75',
        blue: '#66d9ef',
        magenta: '#ae81ff',
        cyan: '#a1efe4',
        white: '#f8f8f2',
        brightBlack: '#75715e',
        brightRed: '#f92672',
        brightGreen: '#a6e22e',
        brightYellow: '#f4bf75',
        brightBlue: '#66d9ef',
        brightMagenta: '#ae81ff',
        brightCyan: '#a1efe4',
        brightWhite: '#f9f8f5',
      ),
    ),
    'solarizedDark': TerminalThemeOption(
      key: 'solarizedDark',
      name: 'Solarized Dark',
      type: 'dark',
      theme: _theme(
        background: '#002b36',
        foreground: '#839496',
        cursor: '#93a1a1',
        selectionBackground: '#839496',
        black: '#073642',
        red: '#dc322f',
        green: '#859900',
        yellow: '#b58900',
        blue: '#268bd2',
        magenta: '#d33682',
        cyan: '#2aa198',
        white: '#eee8d5',
        brightBlack: '#002b36',
        brightRed: '#cb4b16',
        brightGreen: '#586e75',
        brightYellow: '#657b83',
        brightBlue: '#839496',
        brightMagenta: '#6c71c4',
        brightCyan: '#93a1a1',
        brightWhite: '#fdf6e3',
      ),
    ),
    'solarizedLight': TerminalThemeOption(
      key: 'solarizedLight',
      name: 'Solarized Light',
      type: 'light',
      theme: _theme(
        background: '#fdf6e3',
        foreground: '#657b83',
        cursor: '#586e75',
        selectionBackground: '#657b83',
        black: '#073642',
        red: '#dc322f',
        green: '#859900',
        yellow: '#b58900',
        blue: '#268bd2',
        magenta: '#d33682',
        cyan: '#2aa198',
        white: '#eee8d5',
        brightBlack: '#002b36',
        brightRed: '#cb4b16',
        brightGreen: '#586e75',
        brightYellow: '#657b83',
        brightBlue: '#839496',
        brightMagenta: '#6c71c4',
        brightCyan: '#93a1a1',
        brightWhite: '#fdf6e3',
      ),
    ),
    'githubDark': TerminalThemeOption(
      key: 'githubDark',
      name: 'GitHub Dark',
      type: 'dark',
      theme: _theme(
        background: '#0d1117',
        foreground: '#c9d1d9',
        cursor: '#c9d1d9',
        selectionBackground: '#c9d1d9',
        black: '#484f58',
        red: '#ff7b72',
        green: '#3fb950',
        yellow: '#d29922',
        blue: '#58a6ff',
        magenta: '#bc8cff',
        cyan: '#39c5cf',
        white: '#b1bac4',
        brightBlack: '#6e7681',
        brightRed: '#ffa198',
        brightGreen: '#56d364',
        brightYellow: '#e3b341',
        brightBlue: '#79c0ff',
        brightMagenta: '#d2a8ff',
        brightCyan: '#56d364',
        brightWhite: '#f0f6fc',
      ),
    ),
    'githubLight': TerminalThemeOption(
      key: 'githubLight',
      name: 'GitHub Light',
      type: 'light',
      theme: _theme(
        background: '#ffffff',
        foreground: '#000000',
        cursor: '#24292f',
        selectionBackground: '#000000',
        black: '#24292f',
        red: '#cf222e',
        green: '#1a7f37',
        yellow: '#9a6700',
        blue: '#0969da',
        magenta: '#8250df',
        cyan: '#1b7c83',
        white: '#6e7781',
        brightBlack: '#57606a',
        brightRed: '#a40e26',
        brightGreen: '#116329',
        brightYellow: '#4d2d00',
        brightBlue: '#21498c',
        brightMagenta: '#562c99',
        brightCyan: '#12393d',
        brightWhite: '#8c959f',
      ),
    ),
    'vscodeDark': TerminalThemeOption(
      key: 'vscodeDark',
      name: 'VS Code Dark',
      type: 'dark',
      theme: _theme(
        background: '#1e1e1e',
        foreground: '#cccccc',
        cursor: '#ffffff',
        selectionBackground: '#cccccc',
        black: '#000000',
        red: '#cd3131',
        green: '#0dbc79',
        yellow: '#e5e510',
        blue: '#2472c8',
        magenta: '#bc3fbc',
        cyan: '#11a8cd',
        white: '#e5e5e5',
        brightBlack: '#666666',
        brightRed: '#f14c4c',
        brightGreen: '#23d18b',
        brightYellow: '#f5f543',
        brightBlue: '#3b8eea',
        brightMagenta: '#d670d6',
        brightCyan: '#29b8db',
        brightWhite: '#e5e5e5',
      ),
    ),
    'vscodeLight': TerminalThemeOption(
      key: 'vscodeLight',
      name: 'VS Code Light',
      type: 'light',
      theme: _theme(
        background: '#ffffff',
        foreground: '#333333',
        cursor: '#000000',
        selectionBackground: '#333333',
        black: '#000000',
        red: '#cd3131',
        green: '#00bc00',
        yellow: '#949800',
        blue: '#0451a5',
        magenta: '#bc3fbc',
        cyan: '#0598bc',
        white: '#555555',
        brightBlack: '#666666',
        brightRed: '#f14c4c',
        brightGreen: '#23d18b',
        brightYellow: '#f5f543',
        brightBlue: '#3b8eea',
        brightMagenta: '#d670d6',
        brightCyan: '#29b8db',
        brightWhite: '#a5a5a5',
      ),
    ),
  };

  static TerminalTheme resolve(String key, Brightness brightness) {
    if (key == 'auto') {
      return brightness == Brightness.dark
          ? options['vscodeDark']!.theme!
          : options['vscodeLight']!.theme!;
    }
    return options[key]?.theme ?? options['vscodeDark']!.theme!;
  }

  static String nameOf(String key) => options[key]?.name ?? 'VS Code Dark';
}
